package ro.fabio.jetpizza.model

data class Pizza(
    val id: Long,
    val name: String,
    val description: String,
    val imageUrl: String,
    val price: Float,
)

val Pizza.formattedPrice: String
    get() = "%.2f LEI".format(price)

val allPizzas = listOf(
    Pizza(
        id = 0,
        name = "Pizza Abruzzo",
        description = "aluat(faina,apa,ulei de masline extravergin,drojdie ,sare);sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine)mozzarella,salam dulce,masline negre,praz\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Fabio-Pizza4-500.jpg",
        price = 36.00f,
    ),
    Pizza(
        id = 1,
        name = "Pizza Rimini",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),sos alb(mascarpone,smantana),mozzarella,brie,rosii cherry,pui\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Fabio-Pizza2-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 2,
        name = "Pizza Como",
        description = "aluat(faina,apa,ulei de masline extravergin,drojdie ,sare);sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine)mozzarella,salam picant,ciuperci,ardei iute verde\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Fabio-Pizza1-500.jpg",
        price = 36.00f,
    ),
    Pizza(
        id = 3,
        name = "Pizza Levanto",
        description = "aluat(faina,apa,ulei de masline extravergin,drojdie ,sare);sos alb (smantana ,mascarpone),mozzarella,ardei copt,pui la cuptor,gorgonzola,cimbru\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Fabio-Pizza3-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 4,
        name = "Pizza Florenta",
        description = "aluat(faina,apa,ulei de masline extravergin,drojdie ,sare);sos alb (smantana ,mascarpone),mozzarella,sunca,ciuperci,marar\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Fabio-Pizza5-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 5,
        name = "Pizza Cu Praz Si Telemea Artizanala de vaca  Casaria Dunar ",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),telemea de vaca,rosii cherry,praz\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Cu-Praz-Si-Telemea-Artizanala-de-vaca-Casaria-Dunar-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 6,
        name = "Pizza Cu Bacon Si Telemea Artizanala de Vaca  Casaria Dunar",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),telemea de vaca,rosii,bacon,ceapa\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Cu-Bacon-Si-Telemea-Artizanala-de-Vaca-Casaria-Dunar-500.jpg",
        price = 42.00f,
    ),
    Pizza(
        id = 7,
        name = "Pizza Pop Cola Lime Zero",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),dovlecei,rosii cherry,gorgonzola,porumb,patrunjel+POP COLA LIME ZERO 500ML CADOU\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Pop-Cola-Lime-Zero-500.jpg",
        price = 42.00f,
    ),
    Pizza(
        id = 8,
        name = " Pizza Pop Cola Lime",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos alb(smantana,mascarpone),ciuperci,piept de pui grill,marar+POP COLA LIME 500ML CADOU\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Pop-Cola-Lime-500.jpg",
        price = 40.00f,
    ),
    Pizza(
        id = 9,
        name = "Pizza Pop It Louder Veggie",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos alb(smantana,mascarpone),rosii cherry,brie,fenel,baby spanac + POP COLA ZERO 330ml CADOU\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Pop-It-Louder-Veggie-500.jpg",
        price = 40.00f,
    ),
    Pizza(
        id = 10,
        name = "Pizza Pop It Louder Spicy",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie ,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),bacon,salam picant,porumb,ardei verde iute + POP COLA  330ml CADOU\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Pop-It-Louder-Spicy-500.jpg",
        price = 46.00f,
    ),
    Pizza(
        id = 11,
        name = "Pizza Tasty Yellow Cu Filgud",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),branza din caju,broccolli,ciuperci,porumb. Descoperă produsele Filgud aici: https://filgud.ro/\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Tasty-Yellow-cu-Filgud-logo2.jpg",
        price = 46.00f,
    ),
    Pizza(
        id = 12,
        name = "Pizza Tasty Red Cu Filgud",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),branza din caju,rosii cherry,sparanghel,fulgi de migdale. Descoperă produsele Filgud aici: https://filgud.ro/\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Tasty-Red-cu-Filgud-logo2.jpg",
        price = 46.00f,
    ),
    Pizza(
        id = 13,
        name = "Pizza Tasty Green Cu Filgud",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),dovlecel,branza din caju,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),marar. Descoperă produsele Filgud aici: https://filgud.ro/\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Tasty-Green-cu-Filgud-logo2.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 14,
        name = "Pizza Quattro Stagioni",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),salam dulce,ciuperci,ardei gras,masline negre\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Quattro-Stagioni-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 15,
        name = "Pizza Amatriciana",
        description = "aluat(faina,apa,ulei de masline extravergine,grojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine)bacon,porumb,ceapa rosie,gorgonzola\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Amatriciana-500.jpg",
        price = 37.00f,
    ),
    Pizza(
        id = 16,
        name = "Pizza Riccione",
        description = "aluat(faina,apa ,ulei de masline extravergine,drojdie,sare),mozarella,sos alb(smantana,mascarpone),rosii uscate,praz,parmezan\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Riccione-500.jpg",
        price = 30.00f,
    ),
    Pizza(
        id = 17,
        name = "Pizza Margherita",
        description = "aluat(faina ,apa,ulei de masline extravergine,drojdie,sare),sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),mozarella,busuioc verde\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Margherita-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 18,
        name = "Pizza Fabio",
        description = "aluat(faina ,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine)sunca,carnati semiafumati,muschi file,masline,ardei gras,ciuperci\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Fabio-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 19,
        name = "Pizza Paesana",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),bacon,ceapa,sunca,muschi file,ciuperci\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Paesana-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 20,
        name = "Pizza Prosciutto E Funghi",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),ciuperci,sunca\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Prosciutto-E-Funghi-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 21,
        name = "Pizza Capriciosa",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),ciuperci,sunca,ardei gras,masline negre\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Capriciosa-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 22,
        name = "Pizza Carnivora",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),sunca,salam picant,muschi file,salam dulce,carnati semiafumati\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Carnivora-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 23,
        name = "Pizza Diavola ",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),salam picant\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Diavola-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 24,
        name = "Pizza Mexico ",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),ceapa rosie,carnati semiafumati,fasole rosie,salam picant,marar\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Mexico-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 25,
        name = "Pizza Calabrese",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),ardei gras,porumb,cascaval afumat,salam dulce\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Calabrese-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 26,
        name = "Pizza Messina",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),piept de pui grill,bacon,ciuperci,masline verzi\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Messina-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 27,
        name = "Pizza Reggiana",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),rosii cherry,vinete,dovlecei,parmezan,busuioc verde\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Reggiana-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 28,
        name = "Pizza Destate",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,ananas,sunca\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Destate-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 29,
        name = "Pizza Campagnola",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),ceapa rosie,ardei gras,vinete,porumb,masline negre,dovlecei\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Campagnola-500.jpg",
        price = 30.00f,
    ),
    Pizza(
        id = 30,
        name = "Pizza Tonno E Cipole ",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),ton,ceapa rosie\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Tonno-E-Cipole-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 31,
        name = "Pizza Maggiore",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),piept de pui grill,sunca,ciuperci,masline negre\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Maggiore-500.jpg",
        price = 37.00f,
    ),
    Pizza(
        id = 32,
        name = "Pizza Monteverde",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busioc verde,ulei de masline extravergine),prosciutto crudo,rucola,parmezan\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Monteverde-500.jpg",
        price = 30.00f,
    ),
    Pizza(
        id = 33,
        name = "Pizza Torre Del Greco",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella de bivolita,sos de rosii(pulpa de rosii decojite,ulei de masline extarvergine,busuioc verde),rosii cherry,prosciutto crudo,busuioc verde\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Torre-Del-Greco-500.jpg",
        price = 37.00f,
    ),
    Pizza(
        id = 34,
        name = "Pizza Brindisi",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),gorgonzola,ciuperci,prosciutto crudo,masline verzi\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Brindisi-500.jpg",
        price = 28.00f,
    ),
    Pizza(
        id = 35,
        name = "Pizza Modena",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuioc verde,ulei de masline extravergine),sunca,ciuperci,salam picant\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Modena-500.jpg",
        price = 35.00f,
    ),
    Pizza(
        id = 36,
        name = "Pizza Rustica",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde),bacon,ceapa,anghinare,sunca\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Rustica-500.jpg",
        price = 30.00f,
    ),
    Pizza(
        id = 37,
        name = "Pizza Belvedere",
        description = "aluat(faina ,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,ulei de masline extravergine,busuioc verde)dovlecei,telemea de capra,marar\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Belvedere-500.jpg",
        price = 37.00f,
    ),
    Pizza(
        id = 38,
        name = "Pizza Castiglione",
        description = "aluat(faina,apa,ulei de masline extravergine,drojdie,sare),mozarella,sos de rosii(pulpa de rosii decojite,busuic verde,ulei de masline extravergine),rosii cherry,telemea de capra,busuioc verde\n",
        imageUrl = "https://www.fabiopizza.ro/upload/shop/products/Pizza-Castiglione-500.jpg",
        price = 37.00f,
    ),

    )